version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    container_name: my-node-app

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
